config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#index"
  devise_for :users # creates the routes for sign_up, log_out etc
  resources :users, only: [ :show ] # standard routes for the app related user pages
  resources :events, only: [ :create, :new, :show ] do
    resources :attendances, only: [ :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: :user_id
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: "Event"
  has_many :attendances
  has_many :attending_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username ])
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    user = current_user
    event = Event.find(params[:event_id])
    attendance = user.attendances.build(event: event)

    if attendance.save
      redirect_back fallback_location: event_path(event), notice: "You're attending!"
    else
      redirect_back fallback_location: event_path(event), alert: attendance.full_messages.to_sentence
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @user = User.find(current_user.id)
    @event = @user.events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.expect(event: [ :title, :date, :location ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_card.html.erb
<%= tag.div class: "card" do %>
  <%= tag.div class: "card-header" do %>
    <%= link_to event_path(event.id) do %>
      <%= tag.h3 event.title %>
    <% end %>
  <% end %>
  <%= tag.div class: "card-body" do %>
    <%= tag.p event.date %>
    <%= tag.p event.location %>
  <% end %>
  <%= tag.div class: "card-footer" do %>
    <%= button_to "Attend", event_attendances_path(event), class: "btn" %>
  <% end %>
<% end %>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>
<br/ >
<br/ >
<br/ >
<%= link_to "Create Event", new_event_path %>
<br/>
<br/>
<% @events.each do |event| %>
  <%= render partial: "event_card", locals: { event: event } %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>
  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h1>Event Show Page</h1>

<%= render partial: "event_card", locals: { event: @event } %>
<%= tag.h3 "Attendees" %>
<% @event.attendees.each do |a| %>
  <%= tag.p a.email %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Private Events">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<%= tag.nav do %>
  <% if current_user %>
    <%= tag.span "Hello #{current_user.username}"%>
  <% else %>
    <%=  tag.span "No user logged in" %>
  <% end %>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
  <%= link_to 'Sign In', new_user_session_path %>
  <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete } %>
<% end %>

app/views/users/show.html.erb
<h1>User Show Page</h1>
<h3>Created Events</h3>
<% @user.created_events.each do |e| %>
  <p><%= e.title %></p>
  <p><%= e.date %></p>
  <p><%= e.location %></p>
<% end %>
<%= Time.now %>
<h3>Attending Events</h3>
<h3>Past</h3>
<% @user.attending_events.each do |e| %>
  <% if e.date  < Time.now %>
    <p><%= e.title %></p>
    <p><%= e.date %></p>
    <p><%= e.location %></p>
  <% end %>
<% end %>

<h3>Upcoming</h3>
<% @user.attending_events.each do |e| %>
  <% if e.date >= Time.now %>
    <p><%= e.title %></p>
    <p><%= e.date %></p>
    <p><%= e.location %></p>
  <% end %>
<% end %>